// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7uANSShzNd67uIUchKiuKyDf-fz8-CO4',
    appId: '1:369740196405:web:b1fe2edf0375ce7702df7c',
    messagingSenderId: '369740196405',
    projectId: 'my-enfo-hub-6f543',
    authDomain: 'my-enfo-hub-6f543.firebaseapp.com',
    storageBucket: 'my-enfo-hub-6f543.firebasestorage.app',
    measurementId: 'G-Y4SXB7W550',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmEHyf6hOlRrfD3LTTSfrxTdLWFHCMpNY',
    appId: '1:369740196405:android:c4129c18299dbdf002df7c',
    messagingSenderId: '369740196405',
    projectId: 'my-enfo-hub-6f543',
    storageBucket: 'my-enfo-hub-6f543.firebasestorage.app',
  );
}
